import {
  TelegramAccount,
  PublishingTarget,
  Campaign,
  PublishingJob,
  ProxyItem,
  DeliveryLog,
  ErrorLog,
  AuditLog,
  Plan,
} from '../types';

export const SAMPLE_PROXIES: ProxyItem[] = [
  {
    id: 'proxy-p1',
    host: '45.142.195.12',
    port: 8080,
    protocol: 'HTTP',
    regionLabel: 'Amsterdam NL-01',
    country: 'Netherlands',
    publicIp: '45.142.195.12',
    status: 'HEALTHY',
    latencyMs: 65,
    pingMs: 58,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 60000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 2,
    uptimePercent: 99.8,
  },
  {
    id: 'proxy-p2',
    host: '91.240.88.19',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'London UK-02',
    country: 'United Kingdom',
    publicIp: '91.240.88.19',
    status: 'HEALTHY',
    latencyMs: 82,
    pingMs: 76,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 120000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 2,
    uptimePercent: 99.5,
  },
  {
    id: 'proxy-p3',
    host: '194.38.22.77',
    port: 3128,
    protocol: 'HTTPS',
    regionLabel: 'Tehran Dedicated IR-01',
    country: 'Iran',
    publicIp: '194.38.22.77',
    status: 'HEALTHY',
    latencyMs: 38,
    pingMs: 32,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 90000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 1,
    uptimePercent: 99.9,
  },
  {
    id: 'proxy-p4',
    host: '89.208.107.12',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Helsinki FI-01',
    country: 'Finland',
    publicIp: '89.208.107.12',
    status: 'DOWN',
    latencyMs: 0,
    pingMs: 0,
    icmpAvailable: false,
    lastCheck: new Date(Date.now() - 300000).toISOString(),
    failureCount: 14,
    assignedAccountCount: 0,
    uptimePercent: 82.1,
  },
  {
    id: 'proxy-p5',
    host: '142.93.104.88',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Frankfurt DE-02',
    country: 'Germany',
    publicIp: '142.93.104.88',
    status: 'HEALTHY',
    latencyMs: 74,
    pingMs: 68,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 75000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 1,
    uptimePercent: 99.7,
  },
  {
    id: 'proxy-p6',
    host: '178.62.201.33',
    port: 443,
    protocol: 'MTPROXY',
    regionLabel: 'Paris FR-01 (MTProto Secure)',
    country: 'France',
    publicIp: '178.62.201.33',
    status: 'HEALTHY',
    latencyMs: 59,
    pingMs: 52,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 40000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 1,
    uptimePercent: 99.9,
  },
  {
    id: 'proxy-p7',
    host: '185.190.140.22',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Istanbul TR-01',
    country: 'Turkey',
    publicIp: '185.190.140.22',
    status: 'HEALTHY',
    latencyMs: 62,
    pingMs: 55,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 85000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 1,
    uptimePercent: 99.6,
  },
  {
    id: 'proxy-p8',
    host: '104.248.150.91',
    port: 8080,
    protocol: 'HTTP',
    regionLabel: 'New York US-01',
    country: 'United States',
    publicIp: '104.248.150.91',
    status: 'HEALTHY',
    latencyMs: 145,
    pingMs: 138,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 110000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 0,
    uptimePercent: 99.4,
  },
  {
    id: 'proxy-p9',
    host: '139.59.210.44',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Singapore SG-01',
    country: 'Singapore',
    publicIp: '139.59.210.44',
    status: 'HEALTHY',
    latencyMs: 168,
    pingMs: 160,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 95000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 0,
    uptimePercent: 99.3,
  },
  {
    id: 'proxy-p10',
    host: '194.225.10.15',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Shiraz Datacenter IR-02',
    country: 'Iran',
    publicIp: '194.225.10.15',
    status: 'HEALTHY',
    latencyMs: 42,
    pingMs: 36,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 50000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 1,
    uptimePercent: 99.9,
  },
  {
    id: 'proxy-p11',
    host: '167.99.130.55',
    port: 443,
    protocol: 'MTPROXY',
    regionLabel: 'Stockholm SE-01',
    country: 'Sweden',
    publicIp: '167.99.130.55',
    status: 'HEALTHY',
    latencyMs: 78,
    pingMs: 70,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 65000).toISOString(),
    failureCount: 0,
    assignedAccountCount: 0,
    uptimePercent: 99.6,
  },
  {
    id: 'proxy-p12',
    host: '185.220.101.45',
    port: 1080,
    protocol: 'SOCKS5',
    regionLabel: 'Frankfurt DE-01',
    country: 'Germany',
    publicIp: '185.220.101.45',
    status: 'DEGRADED',
    latencyMs: 940,
    pingMs: 890,
    icmpAvailable: true,
    lastCheck: new Date(Date.now() - 180000).toISOString(),
    failureCount: 6,
    assignedAccountCount: 1,
    uptimePercent: 91.4,
  },
];

export const SAMPLE_ACCOUNTS: TelegramAccount[] = [
  {
    id: 'acc-1',
    phone: '+989121110001',
    username: 'ops_telecom_01',
    displayName: 'مدیریت انتشار اخبار اصلی',
    alias: 'News Main Node',
    description: 'اکانت رسمی جهت پخش اطلاعیه‌های فوری در کانال‌های همکار',
    telegramUserId: 'tg_748291038',
    dcId: 4,
    phoneRegion: 'Iran (+98)',
    accountType: 'USER',
    isPremium: true,
    has2FA: true,
    status: 'CONNECTED',
    restrictionStatus: 'NONE_DETECTED',
    proxyId: 'proxy-p1',
    lastSeen: new Date(Date.now() - 30000).toISOString(),
    lastSuccessfulOp: new Date(Date.now() - 120000).toISOString(),
    encryptedSessionHash: 'enc_aes256_sha256_9b82103f8a',
    healthScore: { connection: 'HEALTHY', auth: 'VALID', session: 'HEALTHY', proxy: 'HEALTHY', restrictions: 'NONE' },
    stats: { messagesProcessed: 128, successfulJobs: 126, failedJobs: 2, uptimePercent: 99.4, avgLatencyMs: 72 },
    dialogCount: { total: 420, groups: 142, channels: 31, privateChats: 220, bots: 27 },
    deviceInfo: {
      deviceModel: 'Samsung Galaxy S24 Ultra (SM-S928B)',
      platform: 'Android',
      systemVersion: 'Android 14',
      appVersion: 'Telegram Android 10.9.1',
      langCode: 'fa',
      officialApp: true,
    },
    tags: ['اخبار', 'فوری', 'اصلی'],
    enabled: true,
  },
  {
    id: 'acc-2',
    phone: '+989122220002',
    username: 'growth_dispatch_02',
    displayName: 'مدیر هماهنگی کمپین‌های منطقه‌ای',
    alias: 'Promo Dispatcher',
    description: 'ارسال برنامه‌ریزی‌شده در گروه‌های تخصصی فنی و فناوری',
    telegramUserId: 'tg_859201948',
    dcId: 4,
    phoneRegion: 'Iran (+98)',
    accountType: 'USER',
    isPremium: false,
    has2FA: true,
    status: 'CONNECTED',
    restrictionStatus: 'NONE_DETECTED',
    proxyId: 'proxy-p2',
    lastSeen: new Date(Date.now() - 45000).toISOString(),
    lastSuccessfulOp: new Date(Date.now() - 150000).toISOString(),
    encryptedSessionHash: 'enc_aes256_sha256_7c39201a4e',
    healthScore: { connection: 'HEALTHY', auth: 'VALID', session: 'HEALTHY', proxy: 'HEALTHY', restrictions: 'NONE' },
    stats: { messagesProcessed: 94, successfulJobs: 93, failedJobs: 1, uptimePercent: 99.1, avgLatencyMs: 84 },
    dialogCount: { total: 310, groups: 98, channels: 44, privateChats: 150, bots: 18 },
    deviceInfo: {
      deviceModel: 'iPhone 15 Pro (A3102)',
      platform: 'iOS',
      systemVersion: 'iOS 17.5.1',
      appVersion: 'Telegram iOS 10.12',
      langCode: 'en',
      officialApp: true,
    },
    tags: ['تبلیغات', 'فنی'],
    enabled: true,
  },
  {
    id: 'acc-3',
    phone: '+989123330003',
    username: 'field_operator_03',
    displayName: 'اپراتور پیام‌رسانی میدانی',
    alias: 'Field Node 03',
    description: 'اتصال دارای تاخیر بالا به دلیل کندی پروکسی P12',
    telegramUserId: 'tg_194820394',
    dcId: 4,
    phoneRegion: 'Iran (+98)',
    accountType: 'USER',
    isPremium: true,
    has2FA: true,
    status: 'DEGRADED',
    restrictionStatus: 'NONE_DETECTED',
    proxyId: 'proxy-p12',
    lastSeen: new Date(Date.now() - 90000).toISOString(),
    lastSuccessfulOp: new Date(Date.now() - 900000).toISOString(),
    lastError: 'تاخیر بالای پروکسی فرانکفورت (940ms)',
    encryptedSessionHash: 'enc_aes256_sha256_1f8293a90b',
    healthScore: { connection: 'DEGRADED', auth: 'VALID', session: 'HEALTHY', proxy: 'DEGRADED', restrictions: 'NONE' },
    stats: { messagesProcessed: 68, successfulJobs: 62, failedJobs: 6, uptimePercent: 91.2, avgLatencyMs: 910 },
    dialogCount: { total: 290, groups: 88, channels: 39, privateChats: 145, bots: 18 },
    deviceInfo: {
      deviceModel: 'Xiaomi 13 Pro (2210132G)',
      platform: 'Android',
      systemVersion: 'HyperOS 1.0.8',
      appVersion: 'Telegram Android 10.9.0',
      langCode: 'fa',
      officialApp: true,
    },
    tags: ['تست', 'آزمایشی'],
    enabled: true,
  },
];

export const SAMPLE_TARGETS: PublishingTarget[] = [
  {
    id: 'target-1',
    telegramId: '-1001429841029',
    title: 'جامعه توسعه‌دهندگان نرم‌افزار ایران',
    panelAlias: 'توسعه‌دهندگان وب و سرور',
    description: 'گروه برنامه‌نویسان بک‌اند و معماران نرم‌افزار',
    username: 'ir_tech_developers',
    type: 'SUPERGROUP',
    membershipState: 'JOINED',
    adminState: 'MEMBER',
    permissions: { canSend: true, canPost: false, canInvite: true },
    assignedAccountId: 'acc-1',
    failoverAccountIds: ['acc-2'],
    scheduleIntervalMinutes: 60, // Message interval: 60 min
    syncIntervalMinutes: 10,     // Target metadata sync: 10 min
    scheduleEnabled: true,
    lastSync: new Date(Date.now() - 180000).toISOString(),
    nextSync: new Date(Date.now() + 420000).toISOString(),
    status: 'HEALTHY',
    nextRun: new Date(Date.now() + 1800000).toISOString(),
    memberCount: 2450,
    memberCountLastUpdated: new Date(Date.now() - 180000).toISOString(),
    autoJoinPolicy: 'AUTO',
  },
  {
    id: 'target-2',
    telegramId: '-1001749204910',
    title: 'کانال اطلاع‌رسانی زیرساخت و دواپس',
    panelAlias: 'اطلاعیه‌های دواپس',
    description: 'کانال رسمی اطلاع‌رسانی وضعیت سرورها و نگهداری شبکه',
    username: 'devops_infra_news',
    type: 'CHANNEL',
    membershipState: 'JOINED',
    adminState: 'ADMIN',
    permissions: { canSend: true, canPost: true, canInvite: true },
    assignedAccountId: 'acc-1',
    failoverAccountIds: ['acc-2'],
    scheduleIntervalMinutes: 120, // Message interval: 120 min
    syncIntervalMinutes: 15,      // Target metadata sync: 15 min
    scheduleEnabled: true,
    lastSync: new Date(Date.now() - 300000).toISOString(),
    nextSync: new Date(Date.now() + 600000).toISOString(),
    status: 'HEALTHY',
    nextRun: new Date(Date.now() + 3600000).toISOString(),
    memberCount: 8900,
    memberCountLastUpdated: new Date(Date.now() - 300000).toISOString(),
    autoJoinPolicy: 'AUTO',
  },
  {
    id: 'target-3',
    telegramId: '-1001859302819',
    title: 'انجمن تبادل نظر فناوری‌های ابری',
    panelAlias: 'ابر و کلود کامپیوتر',
    description: 'گروه بحث پیرامون کوبرنتیز و راهکارهای Cloud Native',
    username: 'cloud_architects_fa',
    type: 'GROUP',
    membershipState: 'JOINED',
    adminState: 'MEMBER',
    permissions: { canSend: true, canPost: false, canInvite: false },
    assignedAccountId: 'acc-2',
    failoverAccountIds: ['acc-1'],
    scheduleIntervalMinutes: 180, // Message interval: 180 min
    syncIntervalMinutes: 30,      // Target metadata sync: 30 min
    scheduleEnabled: true,
    lastSync: new Date(Date.now() - 600000).toISOString(),
    nextSync: new Date(Date.now() + 1200000).toISOString(),
    status: 'HEALTHY',
    nextRun: new Date(Date.now() + 5400000).toISOString(),
    memberCount: 1120,
    memberCountLastUpdated: new Date(Date.now() - 600000).toISOString(),
    autoJoinPolicy: 'MANUAL',
  },
];

export const SAMPLE_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    name: 'اطلاعیه به‌روزرسانی سیستم و پایگاه داده',
    status: 'ACTIVE',
    messageContent: `📢 **اطلاعیه نگهداری دوره‌ای زیرساخت**\n\nبه استحضار می‌رساند عملیات ارتقای هسته پردازش داده‌ها در ساعت ۲۳:۰۰ انجام خواهد شد. این فرآیند بدون قطعی خدمات صورت می‌پذیرد.`,
    parseMode: 'MARKDOWN',
    mediaUrls: [],
    targetIds: ['target-1', 'target-2'],
    accountIds: ['acc-1', 'acc-2'],
    scheduleType: 'INTERVAL',
    intervalMinutes: 120,
    timezone: 'Asia/Tehran',
    startTime: '09:00',
    retryPolicy: { maxAttempts: 3, backoffSeconds: [30, 90, 300] },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    totalRuns: 16,
    successfulRuns: 16,
    failedRuns: 0,
  },
  {
    id: 'camp-2',
    name: 'معرفی وبینار تخصصی امنیت زیرساخت تلگرام',
    status: 'READY',
    messageContent: `🔒 **وبینار تخصصی: استانداردهای ایمنی پروتکل MTProto و دفاع در برابر مسدودی حساب**\n\nبرای اطلاعات بیشتر و ثبت‌نام رایگان به وب‌سایت مراجعه فرمایید.`,
    parseMode: 'MARKDOWN',
    mediaUrls: [],
    targetIds: ['target-1', 'target-3'],
    accountIds: ['acc-2'],
    scheduleType: 'DAILY',
    intervalMinutes: 1440,
    timezone: 'Asia/Tehran',
    startTime: '14:00',
    retryPolicy: { maxAttempts: 2, backoffSeconds: [60, 180] },
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    totalRuns: 4,
    successfulRuns: 4,
    failedRuns: 0,
  },
];

export const SAMPLE_JOBS: PublishingJob[] = [
  {
    id: 'job-1',
    campaignId: 'camp-1',
    campaignName: 'اطلاعیه به‌روزرسانی سیستم',
    targetId: 'target-1',
    targetTitle: 'جامعه توسعه‌دهندگان نرم‌افزار ایران',
    accountId: 'acc-1',
    accountPhone: '+989121110001',
    proxyId: 'proxy-p1',
    scheduledAt: new Date(Date.now() + 1800000).toISOString(),
    status: 'QUEUED',
    executionKey: `camp-1_target-1_${Date.now() + 1800000}`,
    attempts: [],
  },
  {
    id: 'job-2',
    campaignId: 'camp-1',
    campaignName: 'اطلاعیه به‌روزرسانی سیستم',
    targetId: 'target-2',
    targetTitle: 'کانال اطلاع‌رسانی زیرساخت و دواپس',
    accountId: 'acc-1',
    accountPhone: '+989121110001',
    proxyId: 'proxy-p1',
    scheduledAt: new Date(Date.now() + 3600000).toISOString(),
    status: 'QUEUED',
    executionKey: `camp-1_target-2_${Date.now() + 3600000}`,
    attempts: [],
  },
];

export const SAMPLE_PLANS: Plan[] = [
  {
    id: 'plan-starter',
    name: 'پلن پایه (Starter)',
    internalName: 'starter_monthly',
    description: 'مناسب کانال‌ها و کسب‌وکارهای نوپا با نیاز به انتشار منظم در حداکثر ۵ گروه',
    price: 490000,
    currency: 'TOMAN',
    durationDays: 30,
    trafficGb: 5,
    trafficPolicy: 'CAPPED',
    features: ['اتصال ۲ حساب تلگرام', 'پشتیبانی از ۱۰ گروه/کانال', 'زمان‌بندی تا فاصله ۱۵ دقیقه', 'گزارش‌گیری اولیه'],
    status: 'ACTIVE',
    displayOrder: 1,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'plan-pro',
    name: 'پلن حرفه‌ای (Professional)',
    internalName: 'pro_monthly',
    description: 'برای تیم‌های بازاریابی و شرکت‌های بزرگ با نیاز به انتشار همزمان و Failover خودکار',
    price: 1290000,
    currency: 'TOMAN',
    durationDays: 30,
    trafficGb: 25,
    trafficPolicy: 'UNLIMITED',
    features: ['اتصال ۱۰ حساب همزمان', 'گروه‌های نامحدود', 'پشتیبانی از پروکسی اختصاصی', 'Failover خودکار حساب', 'تحلیل خطاهای ریشه‌ای'],
    status: 'ACTIVE',
    displayOrder: 2,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'plan-enterprise',
    name: 'پلن سازمانی (Enterprise)',
    internalName: 'enterprise_annual',
    description: 'زیرساخت اختصاصی با پایش اختصاصی، بکاپ ساعتی ابری و گارانتی آپ‌تایم ۹۹.۹٪',
    price: 9900000,
    currency: 'TOMAN',
    durationDays: 365,
    trafficGb: 200,
    trafficPolicy: 'UNLIMITED',
    features: ['تعداد اکانت نامحدود', 'پروکسی‌های چندمسیره MTProxy', 'بکاپ خودکار و رمزنگاری‌شده', 'سرویس‌دهی اختصاصی SLA', 'پشتیبانی ۲۴/۷ تلفنی'],
    status: 'ACTIVE',
    displayOrder: 3,
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const SAMPLE_DELIVERY_LOGS: DeliveryLog[] = [
  {
    id: 'dlog-1',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    campaignName: 'اطلاعیه به‌روزرسانی سیستم',
    targetTitle: 'جامعه توسعه‌دهندگان نرم‌افزار ایران',
    accountPhone: '+989121110001',
    proxyLabel: 'P1 (Amsterdam)',
    messagePreview: '📢 اطلاعیه نگهداری دوره‌ای زیرساخت...',
    status: 'SUCCESS',
    durationMs: 480,
  },
  {
    id: 'dlog-2',
    timestamp: new Date(Date.now() - 360000).toISOString(),
    campaignName: 'اطلاعیه به‌روزرسانی سیستم',
    targetTitle: 'کانال اطلاع‌رسانی زیرساخت و دواپس',
    accountPhone: '+989121110001',
    proxyLabel: 'P1 (Amsterdam)',
    messagePreview: '📢 اطلاعیه نگهداری دوره‌ای زیرساخت...',
    status: 'SUCCESS',
    durationMs: 310,
  },
];
